# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v6ehmZ3WmfHFryXsZmXFjEFMtjstKDxZ

PYTHON BASICS
"""

s = "Hi there Sri!"
s.split()
['Hi', 'there', 'Sri!']

"""Use .format() to print the following string.

Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Neptune"
diameter = 49244

print('The diameter of {} is {} kilometers.'.format(planet,diameter))

"""In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d.get('k1')

d['k1']

d['k1'][3]

d['k1'][3]['tricky']

d['k1'][3]['tricky'][3]

d['k1'][3]['tricky'][3]['target']

d['k1'][3]['tricky'][3]['target'][3]

"""NUMPY

"""

import numpy as np

"""4.1 Create an array of 10 zeros?

"""

np.zeros(10)

"""4.2 Create an array of 10 fives?

"""

np.ones(10) * 5

"""5. Create an array of all the even integers from 20 to 35

"""

np.arange(20,36,2)

"""6. Create a 3x3 matrix with values ranging from 0 to 8

"""

np.arange(9).reshape(3,3)

"""7. Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

"""

a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a, b))

"""PANDAS 
8. Create a dataframe with 3 rows and 2 columns

"""

import pandas as pd
record = {
  "Name": ["Mahesh", "Nathan", "Vamsi"],
    
   "Marks": [9, 19, 20]}

"""9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

"""

from datetime import datetime, timedelta

def date_range(start, end):
    delta = end - start  # as timedelta
    days = [start + timedelta(days=i) for i in range(delta.days + 1)]
    return days

start_date = datetime(2023, 1, 1)
end_date = datetime(2023, 2, 10)
    
print(date_range(start_date, end_date))

"""10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]


"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['S.No', 'Name', 'Age']) 
print(df )